package com.cm.config;

public enum CanonicalErrorCodes {
	INVALID_CLIENT_KEY("INVALID_CLIENT_KEY"), DEVICE_REGISTRATION_ID_DEPRECATED(
			"DEVICE_REGISTRATION_ID_DEPRECATED"), DEVICE_REGISTRATION_ID_DELETED(
			"DEVICE_REGISTRATION_ID_DELETED"), DEVICE_HAS_MULTIPLE_REGISTRATIONS(
			"DEVICE_HAS_MULTIPLE_REGISTRATIONS"), DEVICE_NOT_REGISTERED(
			"DEVICE_NOT_REGISTERED"), MISSING_TRACKING_ID("MISSING_TRACKING_ID"), MISSING_CLIENT_KEY(
			"MISSING_CLIENT_KEY"), MISSING_GCM_ID("MISSING_GCM_ID"), MISSING_DEPRECATED_GCM_ID(
			"MISSING_DEPRECATED_GCM_ID"), UPDATED_SDK_AVAILABLE(
			"UPDATED_SDK_AVAILABLE");

	private String value;

	private CanonicalErrorCodes(String value) {
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

}